goekoproject/frontend

goeko/apps/goeko/src/app/demo/demo-result/demo-result.component.html
goeko/apps/goeko/src/app/demo/demo-result/demo-result.component.ts

Do not merge without merging https://github.com/goekoproject/goeko-backend/pull/65

[NO-TICKET] Simplification of classification object

---

goeko/libs/store/src/lib/sme/ecosolution-recomendations.model.ts
goeko/libs/store/src/lib/sme/project.services.ts
goeko/libs/store/src/lib/sme/sme.services.ts

Deploy when [PR](https://github.com/goekoproject/goeko-backend/pull/98) is merged

[NO-TICKET] Renaming recommendation endpoints ecosolution search

---

goeko/apps/goeko/src/app/home/document-legal/document-legal.component.html
goeko/libs/ui/src/styles/buttons.scss

Home button added to cookies policy and privacy policy and margin added to go-button in scss

Added button-home in policy

---

goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/assets/i18n/gb.json

The text in paybackPeriodYears is changed in all languages.

text paybackPeriodYears changed

---

goeko/apps/goeko/src/app/dashboard/dashboard.module.ts
goeko/apps/goeko/src/app/dashboard/dashboard/dashboard-sme.component.html
goeko/apps/goeko/src/app/dashboard/dashboard/dashboard-sme.component.scss
goeko/apps/goeko/src/app/dashboard/dashboard/dashboard-sme.component.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-form.module.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-request/sme-request.component.html
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/ecosolution-list/ecosolution-list.component.html
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/ecosolution-list/ecosolution-list.component.scss
goeko/apps/goeko/src/app/sme-analysis-form/sme-form-analysis/sme-form-analysis.component.html
goeko/apps/goeko/src/app/sme-analysis-form/sme-form-analysis/sme-form-analysis.component.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-form-base/sme-form-base.component.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-form-project/sme-form-project.component.ts
goeko/libs/store/src/lib/sme/project.services.ts
goeko/libs/store/src/lib/sme/sme-request.model.ts
goeko/libs/ui/src/lib/utils/pipes/go-data-format.pipe.ts
goeko/libs/ui/src/lib/utils/pipes/public-api.ts
goeko/libs/ui/src/styles/buttons.scss
goeko/package-lock.json
goeko/package.json

Add lib moment js for format date utc with local
Fix show  detial project 
fix style

add lib moment and fix show project

---

goeko/apps/goeko/src/assets/i18n/fr.json

Corrected text in fr.json for back button "Dos" changed for "Retour"

Correction in backbutton(fr) "Dos" changed for "Retour"

---

goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/assets/i18n/gb.json

Changed text(message) in leadFormTitle, in form sme for contact with the cleantech

Changed text for message sme contact with the cleantech

---

goeko/apps/goeko/src/app/profile/profile/profile-form.ts

Added Validators.required (Obligatoire) in email in profile-form for sme

Validators required in email sme

---

goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/assets/i18n/gb.json

Changed text in all languages in button in resumé / modifier selection, now is actualiser

Changed text in button actualiser in modifier selection

---

goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/result-detail-ecosolution/result-detail-ecosolution.component.html
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json

Correction in email text for french language in conection lead cleantech (conCtacter - contacter) and logic with control structure for "temps de retour sur investissement…": années.

Correction in french text in leads message and logic control structure for year-years

---

goeko/apps/goeko/src/app/app.component.html
goeko/apps/goeko/src/app/app.component.scss
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/assets/i18n/gb.json

Message subscription contact and changes in languages

Message-subscription-contact

---

goeko/apps/goeko/src/app/home/header/header.component.scss

Changes in img logo for size width and min-width for Landing Page

Changes in logo GoEko size

---

goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/assets/i18n/gb.json

In sme > card eco-solution > changed text in all laguages for technicalDescription

Changed text in all languages for technicalDescription

---

goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-request/sme-analysis-request.component.ts

Added a new function for analysis deleted, warning message before delete analysis in sme

Warning message before delete sme analysis

---

goeko/libs/business-ui/src/lib/components/select-subcategory-product/select-subcategory-product.component.html

Added possibility of click in subcategories field in sme and added hover effect (border) subcategories.

Changes in click subcategories and hover effect in sme

---

goeko/apps/goeko/src/app/app.module.ts
goeko/apps/goeko/src/app/profile/profile-routing.module.ts
goeko/apps/goeko/src/app/profile/profile.module.ts
goeko/apps/goeko/src/app/profile/profile/profile.component.html
goeko/apps/goeko/src/app/profile/profile/profile.component.ts
goeko/apps/goeko/src/app/profile/profile/profile.service.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-request/sme-analysis-request.component.ts
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/assets/i18n/gb.json
goeko/apps/goeko/src/environments/environment.dev.ts
goeko/libs/business-ui/src/index.ts
goeko/libs/business-ui/src/lib/guards/exist-user-data.guard.ts
goeko/libs/business-ui/src/lib/guards/public-api.ts
goeko/libs/core/src/lib/config/config.module.ts
goeko/libs/core/src/lib/config/models/options.interface.ts
goeko/libs/core/src/lib/config/modules/auth/auth.service.ts
goeko/libs/store/src/lib/user/user.services.ts

fix flow profile

---

goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/ecosolution-list/ecosolution-list.component.html
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/ecosolution-list/ecosolution-list.component.ts
goeko/libs/business-ui/src/lib/components/sdg-icons/sdg-icons.component.scss
goeko/libs/business-ui/src/lib/components/sdg-icons/sdg-icons.component.ts

Changes in ODS in actor sme for ecosolution list, sdg-icons

Changes in ods icons in ecosolution list for sme

---

goeko/apps/goeko/src/app/sme-analysis-form/form-field.model.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-form.module.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-request/sme-analysis-request.component.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-request/sme-request.component.html
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/ecosolution-list/criteria-ecosolution-search.model.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-result/ecosolution-list/ecosolution-list.component.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-summary/sme-analysis-summary.component.html
goeko/apps/goeko/src/app/sme-analysis-form/sme-analysis-summary/sme-analysis-summary.component.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-form-analysis/sme-analysis.request.ts
goeko/apps/goeko/src/app/sme-analysis-form/sme-form-analysis/sme-form-analysis.component.ts
goeko/apps/goeko/src/assets/i18n/en.json
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json
goeko/apps/goeko/src/tailwind-styles.scss
goeko/libs/store/src/lib/sme/sme-request.model.ts
goeko/libs/ui/src/lib/ui/notification/notification.component.html
goeko/libs/ui/src/lib/ui/switch/public-api.ts
goeko/libs/ui/src/lib/ui/switch/switch.component.html
goeko/libs/ui/src/lib/ui/switch/switch.component.ts
goeko/libs/ui/src/lib/ui/switch/switch.module.ts
goeko/libs/ui/src/lib/ui/switch/toggle-switch.component.ts

- Request list with icon bell if this request be enabled receive notification for email
- toogle switch on resumen page for enable receive notificatuion for emil for new mach

refactor: Update authentication service to use new user service method

---

goeko/apps/goeko/src/assets/i18n/en.json
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json

All languages changed in products

languages in products changed

---

goeko/apps/goeko/src/assets/i18n/en.json
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json

Changes in cleantech form in text all languages and in button English (UK)

Changes in text for cleantech form

---

goeko/apps/goeko/src/assets/i18n/en.json
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json

Changed texts in products becase it was uppercase in some words in subcategories and title page categories. Changed hazardous products also.

Changes in uppercase letters in products for subcategories and title categories

---

goeko/apps/goeko/src/assets/i18n/en.json
goeko/apps/goeko/src/assets/i18n/es.json
goeko/apps/goeko/src/assets/i18n/fr.json

Changed text in all languages for sme message notifications

Changed text in message notifications in sme for all languages

---

goeko/apps/goeko/src/assets/i18n/en.json
goeko/apps/goeko/src/assets/i18n/es.json

Changes in text for ecosolution card in types of toxic products ecosolution card

Changes in english and spanish text in produits toxiques ecosolution card

---

goeko/apps/goeko/src/environments/environment.prod.ts

chore: Update domainAuth0 in environment.prod.ts to 'login.goeko.ch'

---

goeko/apps/goeko/src/app/admin/data-admin/admin-headers.constants.ts
goeko/apps/goeko/src/app/admin/data-admin/admin-users.component.html
goeko/apps/goeko/src/app/admin/data-admin/admin-users.component.ts

Added new field in admin panel for creation date with pipe goDateFormat

New field creation date for admin panel added
